// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fun5
SEXP fun5(NumericMatrix yy_g);
RcppExport SEXP _NanoStringDiff_fun5(SEXP yy_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type yy_g(yy_gSEXP);
    rcpp_result_gen = Rcpp::wrap(fun5(yy_g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NanoStringDiff_fun5", (DL_FUNC) &_NanoStringDiff_fun5, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_NanoStringDiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
